apiVersion: v1
kind: Pod
metadata:
  name: target-nginx
  labels:
    app: target
spec:
  nodeName: k8s-worker1
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: source-curl
  labels:
    app: source
spec:
  nodeName: k8s-worker2
  containers:
  - name: curl
    image: curlimages/curl
    # command to keep the pod running for testing
    command: ["/bin/sh", "-c", "sleep 3600"]